name: TS - CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/go-ci.yaml"
      - "**.go"
      - "apps/backend/**"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/go-ci.yaml"
      - "**.go"
      - "apps/backend/**"

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.x
          cache-dependency-path: "go.sum"

      - name: golangci-lint
        run: |
          go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6
          make lint

      - name: Build backend
        run: |
          make backend
